# Generated by Django 4.2.7 on 2023-11-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocoding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='capital_marker',
            field=models.IntegerField(choices=[(0, 'Other'), (1, 'Area Center'), (2, 'Region Center'), (3, 'Region Area Center'), (4, 'Central Area')], default=0),
        ),
        migrations.AlterField(
            model_name='address',
            name='fias_level',
            field=models.IntegerField(choices=[(0, 'Country'), (1, 'Region'), (3, 'Area'), (4, 'City'), (5, 'City Area'), (6, 'Locality'), (7, 'Street'), (8, 'House'), (9, 'Apartment'), (65, 'Struct'), (90, 'Additional Territory'), (91, 'Additional Ter Street'), (-1, 'Foreign Or Empty')], default=-1),
        ),
    ]
