# Generated by Django 4.2.7 on 2023-11-28 11:39

from django.db import migrations, models
import geocoding.validators


class Migration(migrations.Migration):

    dependencies = [
        ('geocoding', '0002_alter_address_capital_marker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='area',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='area_type',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='capital_marker',
            field=models.IntegerField(choices=[(0, 'Other'), (1, 'Area Center'), (2, 'Region Center'), (3, 'Region Area Center'), (4, 'Central Area')], default=0),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(default=None, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='city_type',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='fias_level',
            field=models.IntegerField(choices=[(0, 'Country'), (1, 'Region'), (3, 'Area'), (4, 'City'), (5, 'City Area'), (6, 'Locality'), (7, 'Street'), (8, 'House'), (9, 'Apartment'), (65, 'Struct'), (90, 'Additional Territory'), (91, 'Additional Ter Street'), (-1, 'Foreign Or Empty')], default=-1),
        ),
        migrations.AlterField(
            model_name='address',
            name='okato',
            field=models.CharField(default=None, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='oktmo',
            field=models.CharField(default=None, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='population',
            field=models.BigIntegerField(default=None, null=True, validators=[geocoding.validators.validate_population]),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(default=None, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='settlement',
            field=models.CharField(default=None, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='settlement_type',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='tax_office',
            field=models.CharField(default=None, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='timezone',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
